/**
 * Civic Ledger design reminder: localization must preserve the evidence hierarchy,
 * risk semantics, and concise institutional language in English and Hindi.
 */
import { useEffect } from "react";

type Language = "EN" | "HI";

const hindiCopy: Record<string, string> = {
  "Evidence for the work that moves the nation.": "राष्ट्र को आगे बढ़ाने वाले कार्यों के लिए साक्ष्य।",
  "A role-aware intelligence platform for finding emerging project risk, examining contributing conditions, and focusing timely review.": "उभरते परियोजना जोखिमों को खोजने, सहायक स्थितियों की जाँच करने और समयबद्ध समीक्षा पर ध्यान केंद्रित करने के लिए भूमिका-आधारित इंटेलिजेंस प्लेटफ़ॉर्म।",
  "Sign in to a workspace.": "अपने कार्यस्थान में साइन इन करें।",
  "Choose the monitoring context you want to review, then enter demo credentials.": "समीक्षा के लिए निगरानी संदर्भ चुनें, फिर डेमो क्रेडेंशियल दर्ज करें।",
  "Use any valid email and a password of four or more characters for this prototype. Enter an email containing “error” to review the sign-in error state.": "इस प्रोटोटाइप में कोई भी मान्य ईमेल और चार या अधिक अक्षरों का पासवर्ड इस्तेमाल करें। त्रुटि स्थिति देखने के लिए ऐसे ईमेल का उपयोग करें जिसमें “error” लिखा हो।",
  "Enter a valid official email address to continue.": "आगे बढ़ने के लिए एक मान्य आधिकारिक ईमेल पता दर्ज करें।",
  "Enter your password to continue.": "आगे बढ़ने के लिए अपना पासवर्ड दर्ज करें।",
  "We could not verify those sign-in details. Review the email and password, then try again.": "इन साइन-इन विवरणों की पुष्टि नहीं हो सकी। ईमेल और पासवर्ड की जाँच कर फिर से प्रयास करें।",
  "Enter a valid official email address to request recovery.": "पासवर्ड पुनर्प्राप्ति के लिए एक मान्य आधिकारिक ईमेल पता दर्ज करें।",
  "Recover your access.": "अपना एक्सेस पुनर्प्राप्त करें।",
  "Enter the official email associated with your PAIMANA-AI account. We will send recovery instructions if the account is registered.": "अपने PAIMANA-AI खाते से जुड़ा आधिकारिक ईमेल दर्ज करें। खाता पंजीकृत होने पर पुनर्प्राप्ति निर्देश भेजे जाएंगे।",
  "For security, the recovery result does not reveal whether an email address is registered.": "सुरक्षा के लिए पुनर्प्राप्ति परिणाम यह नहीं बताता कि ईमेल पता पंजीकृत है या नहीं।",
  "Recovery request recorded": "पुनर्प्राप्ति अनुरोध दर्ज किया गया",
  "Check your inbox.": "अपना इनबॉक्स देखें।",
  "password recovery instructions will be sent shortly.": "पासवर्ड पुनर्प्राप्ति निर्देश शीघ्र भेजे जाएंगे।",
  "Return to sign in": "साइन इन पर वापस जाएँ",
  "Back to sign in": "साइन इन पर वापस जाएँ",
  "Forgot Password?": "पासवर्ड भूल गए?",
  "Official email address": "आधिकारिक ईमेल पता",
  "Password": "पासवर्ड",
  "Enter your password": "अपना पासवर्ड दर्ज करें",
  "Checking access…": "एक्सेस की जाँच हो रही है…",
  "Sending recovery link…": "पुनर्प्राप्ति लिंक भेजा जा रहा है…",
  "Send recovery instructions": "पुनर्प्राप्ति निर्देश भेजें",
  "Demo workspace": "डेमो कार्यस्थान",
  "Decision support workspace": "निर्णय सहायता कार्यस्थान",
  "PREDICT": "पूर्वानुमान",
  "EXPLAIN": "समझें",
  "WARN": "चेतावनी",
  "ACT": "कार्य करें",
  "PAIMANA-AI DEMO ACCESS": "PAIMANA-AI डेमो एक्सेस",
  "Minister / Senior Leadership": "मंत्री / वरिष्ठ नेतृत्व",
  "Senior Monitoring Officer": "वरिष्ठ निगरानी अधिकारी",
  "Ministry / Department Officer": "मंत्रालय / विभाग अधिकारी",
  "Project / Implementing Agency Officer": "परियोजना / कार्यान्वयन एजेंसी अधिकारी",
  "Sign in as Minister": "मंत्री के रूप में साइन इन करें",
  "Sign in as Monitoring Officer": "निगरानी अधिकारी के रूप में साइन इन करें",
  "Sign in as Ministry Officer": "मंत्रालय अधिकारी के रूप में साइन इन करें",
  "Sign in as Project Officer": "परियोजना अधिकारी के रूप में साइन इन करें",
  "Sign in as ": "",
  "Monitoring Officer": "निगरानी अधिकारी के रूप में साइन इन करें",
  "Minister": "मंत्री के रूप में साइन इन करें",
  "Ministry Officer": "मंत्रालय अधिकारी के रूप में साइन इन करें",
  "Project Officer": "परियोजना अधिकारी के रूप में साइन इन करें",
  "Command Center": "कमांड सेंटर",
  "Early Warnings": "पूर्व चेतावनियाँ",
  "Risk Intelligence": "जोखिम विश्लेषण",
  "AI Assistant": "एआई सहायक",
  "Projects": "परियोजनाएँ",
  "Analytics": "विश्लेषण",
  "Settings": "सेटिंग्स",
  "National Infrastructure Portfolio": "राष्ट्रीय अवसंरचना पोर्टफोलियो",
  "Infrastructure Portfolio": "अवसंरचना पोर्टफोलियो",
  "Your Ministry Portfolio": "आपके मंत्रालय का पोर्टफोलियो",
  "Assigned Project Portfolio": "निर्धारित परियोजना पोर्टफोलियो",
  "Monitor project health, emerging risks, and early warnings across the active portfolio.": "सक्रिय पोर्टफोलियो में परियोजना स्थिति, उभरते जोखिम और पूर्व चेतावनियों की निगरानी करें।",
  "A concise national perspective on signals that warrant senior review.": "वरिष्ठ समीक्षा की आवश्यकता वाले संकेतों पर संक्षिप्त राष्ट्रीय दृष्टिकोण।",
  "Review projects, emerging exceptions, and intelligence within your authorised monitoring scope.": "अपने अधिकृत निगरानी दायरे में परियोजनाओं, उभरते अपवादों और इंटेलिजेंस की समीक्षा करें।",
  "Focus on progress, upcoming milestones, and early risk signals across your assigned projects.": "निर्धारित परियोजनाओं में प्रगति, आगामी माइलस्टोन और शुरुआती जोखिम संकेतों पर ध्यान दें।",
  "Portfolio snapshot": "पोर्टफोलियो स्नैपशॉट",
  "Monitoring data current to April 2026.": "निगरानी डेटा अप्रैल 2026 तक अद्यतन है।",
  "Portfolio signal": "पोर्टफोलियो संकेत",
  "Transport & Logistics continues to carry the highest sector-level portfolio risk.": "परिवहन और लॉजिस्टिक्स में सेक्टर स्तर पर सबसे अधिक पोर्टफोलियो जोखिम बना हुआ है।",
  "Two assigned projects carry high-priority delivery conditions.": "दो निर्धारित परियोजनाओं में उच्च-प्राथमिकता वितरण स्थितियाँ हैं।",
  "Investigate portfolio": "पोर्टफोलियो की जाँच करें",
  "View sector analysis": "सेक्टर विश्लेषण देखें",
  "Total projects": "कुल परियोजनाएँ",
  "Assigned projects": "निर्धारित परियोजनाएँ",
  "Critical projects": "गंभीर परियोजनाएँ",
  "High risk": "उच्च जोखिम",
  "Average risk": "औसत जोखिम",
  "Physical progress": "भौतिक प्रगति",
  "Financial progress": "वित्तीय प्रगति",
  "Active monitored portfolio": "सक्रिय निगरानी पोर्टफोलियो",
  "Requiring immediate review": "तत्काल समीक्षा आवश्यक",
  "Elevated monitoring conditions": "उच्च निगरानी स्थितियाँ",
  "Portfolio risk score": "पोर्टफोलियो जोखिम स्कोर",
  "Risk distribution": "जोखिम वितरण",
  "Portfolio signal mix": "पोर्टफोलियो संकेत मिश्रण",
  "Explore projects": "परियोजनाएँ देखें",
  "Risk trajectory": "जोखिम प्रवृत्ति",
  "Portfolio risk trend": "पोर्टफोलियो जोखिम प्रवृत्ति",
  "Interpretation:": "व्याख्या:",
  "the overall risk trend has increased across the last six reporting periods, with schedule conditions as the primary driver.": "पिछली छह रिपोर्टिंग अवधियों में समग्र जोखिम प्रवृत्ति बढ़ी है, जिसमें समय-सारणी स्थितियाँ मुख्य कारक हैं।",
  "Sector comparison": "सेक्टर तुलना",
  "Highest risk sectors": "सर्वाधिक जोखिम वाले सेक्टर",
  "Compare sector performance": "सेक्टर प्रदर्शन की तुलना करें",
  "Priority register": "प्राथमिकता रजिस्टर",
  "Inspect critical register": "गंभीर रजिस्टर देखें",
  "AI executive briefing": "एआई कार्यकारी संक्षेप",
  "The portfolio is signalling a schedule-led concentration of risk.": "पोर्टफोलियो समय-सारणी आधारित जोखिम एकाग्रता का संकेत दे रहा है।",
  "There are": "वर्तमान में",
  "requiring attention.": "परियोजनाओं पर ध्यान आवश्यक है।",
  "Review critical projects": "गंभीर परियोजनाओं की समीक्षा करें",
  "Ask the assistant": "सहायक से पूछें",
  "Recent warnings": "हाल की चेतावनियाँ",
  "Requires investigation": "जाँच आवश्यक",
  "Schedule delay risk": "समय-सारणी विलंब जोखिम",
  "Cost escalation risk": "लागत वृद्धि जोखिम",
  "Progress deviation": "प्रगति विचलन",
  "Project Explorer": "परियोजना एक्सप्लोरर",
  "Portfolio register": "पोर्टफोलियो रजिस्टर",
  "Search, compare, and investigate the active infrastructure portfolio.": "सक्रिय अवसंरचना पोर्टफोलियो में खोजें, तुलना करें और जाँच करें।",
  "All projects": "सभी परियोजनाएँ",
  "Active filters": "सक्रिय फ़िल्टर",
  "Clear all": "सभी साफ़ करें",
  "Result set": "परिणाम सूची",
  "projects shown": "परियोजनाएँ प्रदर्शित",
  "of 1,981 monitored": "1,981 में से निगरानी की गई",
  "Geographic view": "भौगोलिक दृश्य",
  "No evidence matches these conditions.": "इन शर्तों से कोई साक्ष्य मेल नहीं खाता।",
  "Adjust the query or clear the selected risk filter to inspect another part of the register.": "रजिस्टर का अन्य भाग देखने के लिए क्वेरी बदलें या चयनित जोखिम फ़िल्टर साफ़ करें।",
  "Project dossier": "परियोजना डॉसियर",
  "Back to project register": "परियोजना रजिस्टर पर वापस जाएँ",
  "Export to PDF": "पीडीएफ़ में निर्यात करें",
  "Approved budget": "स्वीकृत बजट",
  "Original sanctioned cost": "मूल स्वीकृत लागत",
  "Expenditure": "व्यय",
  "Overall risk": "समग्र जोखिम",
  "Expected delay": "अपेक्षित विलंब",
  "Expected completion": "अपेक्षित पूर्णता",
  "Current forecast": "वर्तमान पूर्वानुमान",
  "Expected date": "अपेक्षित तिथि",
  "AI risk summary": "एआई जोखिम सारांश",
  "Risk condition breakdown": "जोखिम स्थिति विभाजन",
  "Cost overrun risk": "लागत अधिकता जोखिम",
  "Time overrun risk": "समय अधिकता जोखिम",
  "Schedule analysis": "समय-सारणी विश्लेषण",
  "Cost analysis": "लागत विश्लेषण",
  "Risk Factors": "जोखिम कारक",
  "Evidence ledger": "साक्ष्य रजिस्टर",
  "Reporting history": "रिपोर्टिंग इतिहास",
  "Early warning": "पूर्व चेतावनी",
  "Recommended review": "अनुशंसित समीक्षा",
  "Why is this project at risk?": "यह परियोजना जोखिम में क्यों है?",
  "Explainable AI": "व्याख्यात्मक एआई",
  "Search evidence or source record": "साक्ष्य या स्रोत रिकॉर्ड खोजें",
  "Search a reporting period or update": "रिपोर्टिंग अवधि या अद्यतन खोजें",
  "Clear discovery filters": "खोज फ़िल्टर साफ़ करें",
  "No evidence records match this query.": "इस क्वेरी से कोई साक्ष्य रिकॉर्ड मेल नहीं खाता।",
  "No reporting updates match this query.": "इस क्वेरी से कोई रिपोर्टिंग अद्यतन मेल नहीं खाता।",
  "Project Intelligence Assistant": "परियोजना इंटेलिजेंस सहायक",
  "Query the evidence ledger": "साक्ष्य रजिस्टर से पूछें",
  "Use natural language to examine risk conditions, project evidence, and comparative signals.": "जोखिम स्थितियों, परियोजना साक्ष्य और तुलनात्मक संकेतों की जाँच के लिए प्राकृतिक भाषा का उपयोग करें।",
  "Suggested enquiries": "सुझाई गई जाँच",
  "Begin an inspection.": "जाँच प्रारंभ करें।",
  "Explain 619073 risk conditions": "619073 जोखिम स्थितियाँ समझाएँ",
  "Which sector needs priority review?": "किस सेक्टर को प्राथमिक समीक्षा चाहिए?",
  "Inspect critical project register": "गंभीर परियोजना रजिस्टर देखें",
  "Portfolio context enabled": "पोर्टफोलियो संदर्भ सक्रिय",
  "I can help you locate project risk, inspect contributing conditions, and compare portfolio signals. What would you like to examine?": "मैं परियोजना जोखिम खोजने, सहायक स्थितियों की जाँच करने और पोर्टफोलियो संकेतों की तुलना करने में सहायता कर सकता हूँ। आप क्या देखना चाहते हैं?",
  "Transport & Logistics has the highest average sector risk at 68%. It also contains the greatest concentration of critical projects in this monitoring snapshot.": "परिवहन और लॉजिस्टिक्स में औसत सेक्टर जोखिम 68% के साथ सबसे अधिक है। इस निगरानी स्नैपशॉट में गंभीर परियोजनाओं की सबसे अधिक एकाग्रता भी इसी में है।",
  "Project 619073 has a 91% overall risk score. The principal contributing conditions are its physical progress gap, delayed milestones, and expenditure deviation.": "परियोजना 619073 का समग्र जोखिम स्कोर 91% है। मुख्य योगदानकारी स्थितियाँ भौतिक प्रगति अंतर, विलंबित माइलस्टोन और व्यय विचलन हैं।",
  "Inspect Project 619073 dossier": "परियोजना 619073 डॉसियर देखें",
  "Inspect sector analysis": "सेक्टर विश्लेषण দेखें",
  "Workspace preferences": "कार्यस्थान प्राथमिकताएँ",
  "Change interface context": "इंटरफ़ेस संदर्भ बदलें",
  "Demo workspace role": "डेमो कार्यस्थान भूमिका",
  "Interface principles": "इंटरफ़ेस सिद्धांत",
  "Evidence first": "साक्ष्य पहले",
  "Local risk color": "स्थानीय जोखिम रंग",
  "Role-aware view": "भूमिका-आधारित दृश्य",
  "Review desk": "समीक्षा डेस्क",
  "Signed in": "साइन इन",
  "Session active": "सत्र सक्रिय",
  "Active role": "सक्रिय भूमिका",
  "Switch workspace role": "कार्यस्थान भूमिका बदलें",
  "Sign out of PAIMANA-AI": "PAIMANA-AI से साइन आउट करें",
  "LOW": "निम्न",
  "MODERATE": "मध्यम",
  "HIGH": "उच्च",
  "CRITICAL": "गंभीर",
  "Critical": "गंभीर",
  "High": "उच्च",
  "Moderate": "मध्यम",
  "Low": "निम्न",
  "Ongoing": "जारी",
  "Search project, ministry, sector...": "परियोजना, मंत्रालय, सेक्टर खोजें…",
  "Search project name, ID, ministry or sector": "परियोजना नाम, आईडी, मंत्रालय या सेक्टर खोजें",
  "National monitoring": "राष्ट्रीय निगरानी",
  "Workspace": "कार्यस्थान",
  "Snapshot · Apr 2026": "स्नैपशॉट · अप्रैल 2026",
  "Active delivery assignments": "सक्रिय वितरण असाइनमेंट",
  "Projects past key dates": "महत्वपूर्ण तिथियों से आगे की परियोजनाएँ",
  "Across assigned projects": "निर्धारित परियोजनाओं में",
  "2.6% since prior period": "पिछली अवधि से 2.6%",
  "8.4% since prior period": "पिछली अवधि से 8.4%",
  "2.1% since prior period": "पिछली अवधि से 2.1%",
  "3.0 pp since prior period": "पिछली अवधि से 3.0 प्रतिशत अंक",
  "7 milestones due": "7 माइलस्टोन देय",
  "Risk score": "जोखिम स्कोर",
  "Risk mix": "जोखिम मिश्रण",
  "Transport": "परिवहन",
  "Mining": "खनन",
  "Energy": "ऊर्जा",
  "Water": "जल",
  "Communication": "संचार",
  "Project": "परियोजना",
  "Sector": "सेक्टर",
  "Progress": "प्रगति",
  "Risk": "जोखिम",
  "Primary issue": "मुख्य मुद्दा",
  "Project ID": "परियोजना आईडी",
  "Portfolio Analytics · Comparative View": "पोर्टफोलियो विश्लेषण · तुलनात्मक दृश्य",
  "Compare risk concentration, portfolio trends, and sector-level performance.": "जोखिम एकाग्रता, पोर्टफोलियो प्रवृत्तियों और सेक्टर-स्तरीय प्रदर्शन की तुलना करें।",
  "Explore source projects": "स्रोत परियोजनाएँ देखें",
  "Sector risk": "सेक्टर जोखिम",
  "Where average risk is concentrated": "जहाँ औसत जोखिम केंद्रित है",
  "Risk and warnings": "जोखिम और चेतावनियाँ",
  "Portfolio trend compared": "पोर्टफोलियो प्रवृत्ति तुलना",
  "Ministry comparison": "मंत्रालय तुलना",
  "Highest-priority portfolios": "सर्वोच्च-प्राथमिकता पोर्टफोलियो",
  "Ministry": "मंत्रालय",
  "Early Warning Center · Attention Register": "पूर्व चेतावनी केंद्र · ध्यान रजिस्टर",
  "A prioritised register of predicted project conditions requiring monitoring or investigation.": "निगरानी या जाँच आवश्यक अनुमानित परियोजना स्थितियों का प्राथमिकता रजिस्टर।",
  "All warnings": "सभी चेतावनियाँ",
  "Probability": "संभाव्यता",
  "Horizon": "पूर्वानुमान अवधि",
  "Trigger:": "ट्रिगर:",
  "Next 6 months": "अगले 6 महीने",
  "Revised estimate": "संशोधित अनुमान",
  "Current period": "वर्तमान अवधि",
  "Next quarter": "अगली तिमाही",
  "Project Dossier": "परियोजना डॉसियर",
  "Budget, expenditure, and forecast": "बजट, व्यय और पूर्वानुमान",
  "Cost ledger": "लागत रजिस्टर",
  "Revised budget": "संशोधित बजट",
  "Cumulative expenditure": "संचयी व्यय",
  "Forecast outturn": "पूर्वानुमानित परिणाम",
  "Cost overrun signal": "लागत अधिकता संकेत",
  "The forecast should be reconciled against current contractual commitments and approved variation orders.": "पूर्वानुमान का वर्तमान संविदात्मक प्रतिबद्धताओं और स्वीकृत परिवर्तन आदेशों से मिलान किया जाना चाहिए।",
  "Delivery is below the approved trajectory.": "वितरण स्वीकृत प्रगति-पथ से नीचे है।",
  "Completion forecast": "पूर्णता पूर्वानुमान",
  "Project start": "परियोजना प्रारंभ",
  "Original completion": "मूल पूर्णता",
  "Revised completion": "संशोधित पूर्णता",
  "Delivery evidence": "वितरण साक्ष्य",
  "Milestone register": "माइलस्टोन रजिस्टर",
  "Milestone": "माइलस्टोन",
  "Planned": "नियोजित",
  "Observed": "देखा गया",
  "Status": "स्थिति",
  "Land acquisition": "भूमि अधिग्रहण",
  "Foundation works": "नींव कार्य",
  "Structural works": "संरचनात्मक कार्य",
  "Final inspection": "अंतिम निरीक्षण",
  "Complete": "पूर्ण",
  "Delayed": "विलंबित",
  "Forecast": "पूर्वानुमान",
  "The current monitoring snapshot identifies a material likelihood of adverse delivery conditions within the next reporting horizon. Review the contributing signals before escalation.": "वर्तमान निगरानी स्नैपशॉट अगली रिपोर्टिंग अवधि में प्रतिकूल वितरण स्थितियों की महत्वपूर्ण संभावना दर्शाता है। वृद्धि से पहले योगदानकारी संकेतों की समीक्षा करें।",
  "Early warning · active": "पूर्व चेतावनी · सक्रिय",
  "Risk score has increased by 12 points since the January reporting period.": "जनवरी रिपोर्टिंग अवधि से जोखिम स्कोर में 12 अंकों की वृद्धि हुई है।",
  "Inspect contributing factors": "योगदानकारी कारकों की जाँच करें",
  "Reconcile planned and physical progress": "नियोजित और भौतिक प्रगति का मिलान करें",
  "Inspect delayed milestone conditions": "विलंबित माइलस्टोन स्थितियों की जाँच करें",
  "Validate forecast completion date": "पूर्वानुमानित पूर्णता तिथि सत्यापित करें",
  "These are potential investigation areas, not administrative decisions.": "ये संभावित जाँच क्षेत्र हैं, प्रशासनिक निर्णय नहीं।",
  "Model interpretation:": "मॉडल व्याख्या:",
  "the risk profile is driven by delivery progress, milestone status, and cost trajectory rather than one signal in isolation.": "जोखिम प्रोफ़ाइल किसी एक संकेत के बजाय वितरण प्रगति, माइलस्टोन स्थिति और लागत प्रवृत्ति से संचालित है।",
  "Schedule condition": "समय-सारणी स्थिति",
  "Planned progress remains ahead of delivery.": "नियोजित प्रगति वितरण से आगे बनी हुई है।",
  "Inspect schedule": "समय-सारणी की जाँच करें",
  "Actual": "वास्तविक",
  "Explainable AI · SHAP contributors": "व्याख्यात्मक एआई · SHAP योगदानकर्ता",
  "These factors explain how observed project conditions contribute to the model’s risk estimate. They do not establish causality or replace official review.": "ये कारक बताते हैं कि देखी गई परियोजना स्थितियाँ मॉडल के जोखिम अनुमान में कैसे योगदान करती हैं। वे कारण संबंध स्थापित नहीं करते और न ही आधिकारिक समीक्षा का विकल्प हैं।",
  "Physical progress gap": "भौतिक प्रगति अंतर",
  "Milestone delay": "माइलस्टोन विलंब",
  "Expenditure deviation": "व्यय विचलन",
  "Previous schedule revision": "पिछला समय-सारणी संशोधन",
  "Previous reporting periods": "पिछली रिपोर्टिंग अवधियाँ",
  "Risk has steepened across six reporting periods": "छह रिपोर्टिंग अवधियों में जोखिम तेज़ हुआ है",
  "Conditions supporting the current risk view": "वर्तमान जोखिम दृश्य का समर्थन करने वाली स्थितियाँ",
  "Search updates, source records, and document conditions within this project dossier.": "इस परियोजना डॉसियर में अद्यतन, स्रोत रिकॉर्ड और दस्तावेज़ स्थितियाँ खोजें।",
  "Source": "स्रोत",
  "Evidence item": "साक्ष्य विषय",
  "Latest signal": "नवीनतम संकेत",
  "Condition": "स्थिति",
  "Common Upload Form": "सामान्य अपलोड फ़ॉर्म",
  "Financial return": "वित्तीय रिटर्न",
  "Risk engine": "जोखिम इंजन",
  "Needs review": "समीक्षा आवश्यक",
  "Schedule condition has strengthened.": "समय-सारणी स्थिति मजबूत हुई है।",
  "The combined progress gap and delayed structural work now place the project within the current critical warning threshold.": "संयुक्त प्रगति अंतर और विलंबित संरचनात्मक कार्य अब परियोजना को वर्तमान गंभीर चेतावनी सीमा में रखते हैं।",
  "Evidence note": "साक्ष्य टिप्पणी",
  "Evidence should be read alongside approved project reports, field updates, and official monitoring inputs.": "साक्ष्य को स्वीकृत परियोजना रिपोर्टों, क्षेत्रीय अद्यतनों और आधिकारिक निगरानी इनपुट के साथ पढ़ा जाना चाहिए।",
  "Risk score across reporting periods": "रिपोर्टिंग अवधियों में जोखिम स्कोर",
  "Period": "अवधि",
  "Movement": "परिवर्तन",
  "Dominant condition": "प्रमुख स्थिति",
  "Baseline": "आधार रेखा",
  "Rising risk": "बढ़ता जोखिम",
  "All movements": "सभी परिवर्तन",
  "Progress variance": "प्रगति विचरण",
  "Milestone slippage": "माइलस्टोन विचलन",
  "The assistant translates available project intelligence into evidence-led answers and links to the relevant dossier. It does not make administrative decisions.": "सहायक उपलब्ध परियोजना इंटेलिजेंस को साक्ष्य-आधारित उत्तरों में बदलता है और संबंधित डॉसियर से जोड़ता है। यह प्रशासनिक निर्णय नहीं लेता।",
  "Ask about a project, risk condition, or sector...": "परियोजना, जोखिम स्थिति या सेक्टर के बारे में पूछें…",
  "Prototype controls for demonstration scope and interface preferences.": "डेमो दायरे और इंटरफ़ेस प्राथमिकताओं के लिए प्रोटोटाइप नियंत्रण।",
  "Role selection changes the dashboard emphasis and available navigation. In production, these permissions must be authorised by the backend.": "भूमिका चयन डैशबोर्ड प्राथमिकता और उपलब्ध नेविगेशन बदलता है। उत्पादन में इन अनुमतियों को बैकएंड से अधिकृत किया जाना चाहिए।",
  "Metrics retain context, timeframe, and visible status.": "मेट्रिक्स संदर्भ, समय-सीमा और दृश्य स्थिति बनाए रखते हैं।",
  "Critical color appears only where conditions require attention.": "गंभीर रंग केवल वहीं दिखता है जहाँ स्थिति पर ध्यान आवश्यक हो।",
  "Content density responds to the demonstrated role.": "सामग्री घनत्व प्रदर्शित भूमिका के अनुसार बदलता है।",
};

function translate(value: string, language: Language) {
  if (language === "EN") return value;
  return Object.keys(hindiCopy)
    .sort((a, b) => b.length - a.length)
    .reduce((text, english) => text.split(english).join(hindiCopy[english]), value);
}

type SavedTextNode = Text & { paimanaOriginal?: string };

export default function LocalizationLayer({ language }: { language: Language }) {
  useEffect(() => {
    document.documentElement.lang = language === "HI" ? "hi" : "en";
    localStorage.setItem("paimana-language", language);
    const root = document.body;
    const apply = () => {
      const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
      let node = walker.nextNode() as SavedTextNode | null;
      while (node) {
        const parent = node.parentElement;
        if (parent && !["SCRIPT", "STYLE"].includes(parent.tagName) && !parent.closest(".interface-controls")) {
          const original = node.paimanaOriginal ?? node.nodeValue ?? "";
          node.paimanaOriginal = original;
          const next = translate(original, language);
          if (node.nodeValue !== next) node.nodeValue = next;
        }
        node = walker.nextNode() as SavedTextNode | null;
      }
      root.querySelectorAll<HTMLElement>("[placeholder], [aria-label], [title]").forEach((element) => {
        (["placeholder", "aria-label", "title"] as const).forEach((attribute) => {
          const value = element.getAttribute(attribute);
          const saved = element.dataset[`paimana${attribute.replace(/-([a-z])/g, (_, letter: string) => letter.toUpperCase())}`];
          if (value !== null && !saved) element.dataset[`paimana${attribute.replace(/-([a-z])/g, (_, letter: string) => letter.toUpperCase())}`] = value;
          const original = saved ?? value;
          if (original) element.setAttribute(attribute, translate(original, language));
        });
      });
    };
    apply();
    const observer = new MutationObserver(apply);
    observer.observe(root, { childList: true, subtree: true, characterData: true });
    return () => observer.disconnect();
  }, [language]);
  return null;
}
